//! The SMB side: ksmbd (the kernel's SMB2/3 server) serving every mounted
//! volume, which macOS and Windows both speak natively.
//!
//! * `ksmbd.mountd` (ksmbd-tools) is the kernel server's user-space half; it
//!   runs supervised, in the foreground, with this daemon's config and user
//!   database (`ksmbd.mountd -n -C … -P …`). A share change rewrites the config
//!   and `ksmbd.control --reload` picks it up.
//! * Logins: one account, `openhc` by default. Windows 11 refuses guest SMB
//!   logins out of the box, so a password is the default; guest access is an
//!   option for networks that want it. The password lives only as its NT hash
//!   in ksmbd's database (`ksmbd.adduser` writes it), on /data.
//! * Shares force root as the file owner: FAT/exFAT/NTFS have no owners, and
//!   the SMB account is not a Unix one.
//! * macOS finds the box in Finder through an `_smb._tcp` mDNS service (avahi,
//!   which every board runs), published while there is anything to share.
use serde::{Deserialize, Serialize};
use std::path::PathBuf;
use std::process::Command;

pub const RUN: &str = "/run/ohc/storage";
const AVAHI_SERVICE: &str = "/etc/avahi/services/ohc-smb.service";

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, utoipa::ToSchema)]
#[serde(default)]
pub struct Settings {
    /// Serve the drives over SMB at all.
    pub enabled: bool,
    /// The login (letters, digits, `-`, `_`).
    pub user: String,
    /// Allow guest (no password) access as well. Windows 11 blocks guest
    /// logons by default; macOS allows them.
    pub guest: bool,
}

impl Default for Settings {
    fn default() -> Self {
        Settings { enabled: true, user: "openhc".into(), guest: false }
    }
}

fn data_dir() -> PathBuf {
    let data = std::env::var("OHC_DATA").unwrap_or_else(|_| "/data".into());
    let dir = PathBuf::from(data).join("ohc");
    if dir.is_dir() { dir } else { PathBuf::from(RUN) }
}

pub fn settings_path() -> PathBuf {
    data_dir().join("storage.json")
}
pub fn pwddb() -> PathBuf {
    data_dir().join("ksmbdpwd.db")
}
pub fn conf() -> PathBuf {
    PathBuf::from(RUN).join("ksmbd.conf")
}

pub fn load() -> Settings {
    std::fs::read_to_string(settings_path()).ok().and_then(|t| serde_json::from_str(&t).ok()).unwrap_or_default()
}

pub fn save(s: &Settings) -> std::io::Result<()> {
    let p = settings_path();
    let tmp = p.with_extension("json.new");
    std::fs::write(&tmp, serde_json::to_vec_pretty(s)?)?;
    std::fs::rename(&tmp, p)
}

pub fn valid_user(u: &str) -> bool {
    !u.is_empty() && u.len() < 48 && u.chars().all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_')
}

/// An ini value: ksmbd's parser has no quoting, so no newlines, and a share
/// name must not hold `]`.
fn ini(s: &str) -> String {
    s.chars().filter(|c| !c.is_control() && *c != ']' && *c != '[').collect()
}

/// The whole ksmbd.conf for these shares (name, path).
pub fn ksmbd_conf(host: &str, s: &Settings, shares: &[(String, String)]) -> String {
    // NetBIOS names are 15 characters; the hostname is longer on most boards.
    let netbios: String = host.chars().filter(|c| c.is_ascii_alphanumeric() || *c == '-').take(15).collect();
    let mut c = format!(
        "# Generated by ohc-storaged — do not edit.\n[global]\n\tnetbios name = {netbios}\n\tserver string = openHC {host}\n\tworkgroup = WORKGROUP\n\tguest account = nobody\n\tmap to guest = {}\n\tsmb2 leases = yes\n",
        if s.guest { "bad user" } else { "never" },
        host = ini(host),
    );
    for (name, path) in shares {
        c += &format!(
            "\n[{}]\n\tpath = {}\n\tread only = no\n\tbrowseable = yes\n\tguest ok = {}\n{}\tforce user = root\n\tforce group = root\n\tcreate mask = 0666\n\tdirectory mask = 0777\n",
            ini(name),
            ini(path),
            if s.guest { "yes" } else { "no" },
            if s.guest { String::new() } else { format!("\tvalid users = {}\n", ini(&s.user)) },
        );
    }
    c
}

/// Set the account's password in ksmbd's database (replacing it).
pub fn set_password(user: &str, password: &str) -> Result<(), String> {
    if !valid_user(user) {
        return Err(format!("'{user}' is not a valid user name"));
    }
    if password.is_empty() || password.len() > 128 {
        return Err("the password must be 1-128 characters".into());
    }
    let _ = std::fs::create_dir_all(RUN);
    if !conf().exists() {
        let _ = std::fs::write(conf(), ksmbd_conf("openhc", &Settings::default(), &[]));
    }
    let db = pwddb();
    // -a adds, -u updates: try update first, add when the user is new.
    for op in ["-u", "-a"] {
        let o = Command::new("ksmbd.adduser")
            .args(["-P", &db.display().to_string(), "-c", &conf().display().to_string(), op, "-p", password, user])
            .output();
        if matches!(&o, Ok(o) if o.status.success()) {
            return Ok(());
        }
    }
    Err("ksmbd.adduser failed".into())
}

/// Rewrite the config and tell ksmbd.mountd.
pub fn apply(host: &str, s: &Settings, shares: &[(String, String)]) {
    let _ = std::fs::create_dir_all(RUN);
    let text = ksmbd_conf(host, s, if s.enabled { shares } else { &[] });
    if std::fs::read_to_string(conf()).ok().as_deref() != Some(text.as_str()) {
        if let Err(e) = std::fs::write(conf(), &text) {
            eprintln!("storaged: cannot write {}: {e}", conf().display());
        }
        let _ = Command::new("ksmbd.control").arg("--reload").status();
    }
    advertise(s.enabled && !shares.is_empty());
}

/// Publish (or withdraw) the box as an SMB server over mDNS. avahi-daemon
/// watches its services directory, so writing the file is enough.
fn advertise(on: bool) {
    let exists = std::path::Path::new(AVAHI_SERVICE).exists();
    if on && !exists {
        let svc = "<?xml version=\"1.0\" standalone='no'?>\n<!DOCTYPE service-group SYSTEM \"avahi-service.dtd\">\n<!-- Generated by ohc-storaged while drives are shared. -->\n<service-group>\n  <name replace-wildcards=\"yes\">%h</name>\n  <service>\n    <type>_smb._tcp</type>\n    <port>445</port>\n  </service>\n  <service>\n    <type>_device-info._tcp</type>\n    <port>0</port>\n    <txt-record>model=RackMac</txt-record>\n  </service>\n</service-group>\n";
        if let Err(e) = std::fs::write(AVAHI_SERVICE, svc) {
            eprintln!("storaged: cannot write {AVAHI_SERVICE}: {e}");
        }
    } else if !on && exists {
        let _ = std::fs::remove_file(AVAHI_SERVICE);
    }
}

pub fn withdraw() {
    advertise(false);
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn config_with_a_login() {
        let s = Settings::default();
        let c = ksmbd_conf("openhc-hc800-000FFF57B978", &s, &[("Sandisk".into(), "/media/Sandisk".into())]);
        assert!(c.contains("netbios name = openhc-hc800-00"), "{c}");
        assert!(c.contains("map to guest = never"));
        assert!(c.contains("[Sandisk]\n\tpath = /media/Sandisk\n"));
        assert!(c.contains("valid users = openhc\n"));
        assert!(c.contains("guest ok = no"));
        assert!(c.contains("force user = root"));
    }
    #[test]
    fn config_for_guests() {
        let s = Settings { guest: true, ..Settings::default() };
        let c = ksmbd_conf("box", &s, &[("A".into(), "/media/A".into())]);
        assert!(c.contains("map to guest = bad user"));
        assert!(c.contains("guest ok = yes"));
        assert!(!c.contains("valid users"));
    }
    #[test]
    fn names_cannot_break_the_ini() {
        let c = ksmbd_conf("box", &Settings::default(), &[("x]\n[global".into(), "/media/x".into())]);
        assert!(!c.contains("x]"));
        assert_eq!(c.matches("[global]").count(), 1);
    }
    #[test]
    fn user_names() {
        assert!(valid_user("openhc") && valid_user("joe_2"));
        assert!(!valid_user("") && !valid_user("a b") && !valid_user("x:y"));
    }
}
