################################################################################
#
# ohc-motd — /etc/motd generated by figlet at build time
#
# Source-less package: it runs the host's figlet to render the banner straight
# into the target rootfs. The "not in post-build, as a buildroot command" the
# project wants — the figlet call lives in the build graph, gated by
# BR2_PACKAGE_OHC_MOTD, and reruns whenever the package is rebuilt.
#
################################################################################

OHC_MOTD_VERSION = 1.0
OHC_MOTD_SOURCE =
OHC_MOTD_LICENSE = MIT

define OHC_MOTD_INSTALL_TARGET_CMDS
	which figlet >/dev/null 2>&1 || { echo "ohc-motd: figlet missing from build env (build/Dockerfile)"; exit 1; }
	( echo; \
	  figlet -f slant openHC; \
	  echo "  Open, kernel-up firmware for Control4 controllers"; \
	  echo ) > $(TARGET_DIR)/etc/motd
endef

$(eval $(generic-package))
