#!/usr/bin/env bash
# Common post-build hook — runs for EVERY openHC board (wired from
# board/common/common_defconfig). $1 = TARGET_DIR (the assembled rootfs).
#
# This does the ONE thing that has no clean Buildroot-package equivalent: give
# the box an `openhc` login that is uid 0, so `openhc`/`openhc` gets you root —
# the credential the whole project uses. Buildroot's users table refuses uid 0
# for an added user, so it has to be done by editing passwd/shadow here.
#
# The /etc/motd banner is NOT here — it is generated by figlet in the ohc-motd
# Buildroot package (board/package/ohc-motd), not a post-build step.
set -euo pipefail
TARGET="$1"

# BR2_TARGET_GENERIC_ROOT_PASSWD (common_defconfig) already set root's password
# to "openhc", so root's /etc/shadow hash IS the hash of "openhc" — reuse it for
# an `openhc` entry so `openhc`/`openhc` logs in as uid 0. Idempotent.
if ! grep -q '^openhc:' "$TARGET/etc/passwd"; then
    echo 'openhc:x:0:0:openHC:/root:/bin/sh' >> "$TARGET/etc/passwd"
fi
if [ -f "$TARGET/etc/shadow" ] && ! grep -q '^openhc:' "$TARGET/etc/shadow"; then
    hash=$(grep '^root:' "$TARGET/etc/shadow" | cut -d: -f2)
    echo "openhc:${hash}:::::::" >> "$TARGET/etc/shadow"
fi

# Version stamp. The flasher compares this against the latest GitHub release to
# tell whether a box is up to date, so the string MUST match the one CI puts in
# the image/release name: <short-sha>-dev on a normal build, the tag on a
# release. CI exports OHC_VERSION; a local build with none falls back to a git
# describe of the openHC tree, or "dev" if even git is unavailable.
if [ -z "${OHC_VERSION:-}" ]; then
    src="${BR2_EXTERNAL_OPENHC_PATH:-}/.."
    OHC_VERSION="$(git -C "$src" describe --tags --always --dirty 2>/dev/null || echo dev)"
fi

# openHC release marker. The initramfs /init pivots to p1 only when it finds
# this file there — it is what tells a RAM-booted openHC that p1 holds a real
# openHC rootfs (and not the stock Control4 rootfs a factory-restore leaves).
# Stamped with the board, version and build date so `cat /etc/openhc-release` is
# useful and the flasher can read the version back over SSH.
b="${BR2_DEFCONFIG:-openhc}"; b="${b##*/}"
{
    echo "openHC"
    echo "board=${b}"
    echo "version=${OHC_VERSION}"
    echo "built=$(date -u +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || echo unknown)"
} > "$TARGET/etc/openhc-release"

# Also expose it in board.env, the file the flasher already reads to identify a
# unit — one SSH read then yields both board and version. Idempotent across the
# incremental rebuilds that re-run post-build on an existing target.
ENVF="$TARGET/opt/ohc/board.env"
if [ -f "$ENVF" ]; then
    sed -i '/^OHC_VERSION=/d' "$ENVF"
    echo "OHC_VERSION=${OHC_VERSION}" >> "$ENVF"
fi

# Make sure /init (the pivot from the overlay) is executable and switch_root is
# present — a missing applet would strand the box in RAM silently.
chmod +x "$TARGET/init" 2>/dev/null || true
if [ ! -e "$TARGET/sbin/switch_root" ] && [ ! -L "$TARGET/sbin/switch_root" ]; then
    echo "post-build: WARNING /sbin/switch_root missing — busybox needs CONFIG_SWITCH_ROOT" >&2
fi
