//! The music-library player: mpd playing what is on the drives.
//!
//! ohc-storaged mounts every plugged-in drive under /media; mpd (run by this
//! daemon, one instance, when the map has a `library` endpoint) indexes /media
//! and plays to that endpoint's output PCM — so the output's level is its
//! volume and announcements duck it like any other source. mpd's own mixer is
//! off. It listens on loopback only; this daemon is its one client
//! (mpd_client), and everything outside goes through here:
//!
//! * now playing → the same `audio/meta/library-0` every endpoint has (cover
//!   art read from the files through mpd, served at `cover/library-0`);
//! * `audio/library` (retained): play state, position, queue length, whether
//!   the index is updating;
//! * `cmd/audio/library/<verb>`: play, pause, toggle, stop, next, previous,
//!   seek <s>, clear, add <uri>, replace <uri> (clear, add, play), random
//!   <ON|OFF>, repeat <ON|OFF>, update;
//! * REST `GET /api/audio/library/browse?path=` and `/search?q=` to find music.
//!
//! A drive coming or going changes /proc/mounts under /media; the publisher
//! notices and asks mpd to re-index (`mounts_changed`).
use crate::board::Port;
use crate::meta;
use mpd_client::client::{ConnectionEvent, Subsystem};
use mpd_client::commands;
use mpd_client::responses::PlayState;
use mpd_client::Client;
use serde::Serialize;
use serde_json::{json, Value};
use std::sync::{Arc, Mutex};
use std::time::{Duration, SystemTime, UNIX_EPOCH};

pub const MPD: &str = "/usr/bin/mpd";
pub const TAG: &str = "library-0";
pub const MUSIC: &str = "/media";
const ADDR: &str = "127.0.0.1:6600";

fn data_dir() -> String {
    let data = std::env::var("OHC_DATA").unwrap_or_else(|_| "/data".into());
    let dir = std::path::Path::new(&data).join("ohc");
    if dir.is_dir() { dir.join("mpd").display().to_string() } else { "/run/ohc/audio/mpd".into() }
}

/// mpd.conf for a library on `out`. The index and the play state live on
/// /data, so a reboot does not re-scan every drive or forget the queue.
pub fn mpd_conf(out: &Port) -> String {
    let d = data_dir();
    let _ = std::fs::create_dir_all(format!("{d}/playlists"));
    let _ = std::fs::create_dir_all(MUSIC);
    format!(
        "# Generated by ohc-audiod — do not edit.\nmusic_directory \"{MUSIC}\"\ndb_file \"{d}/database\"\nstate_file \"{d}/state\"\nplaylist_directory \"{d}/playlists\"\nbind_to_address \"127.0.0.1\"\nport \"6600\"\nauto_update \"no\"\nfollow_outside_symlinks \"no\"\nfilesystem_charset \"UTF-8\"\nrestore_paused \"yes\"\naudio_output {{\n    type \"alsa\"\n    name \"{label}\"\n    device \"{pcm}\"\n    mixer_type \"none\"\n}}\n",
        label = out.label.replace('"', "'"),
        pcm = out.pcm,
    )
}

/// What the player is doing, for `audio/library`.
#[derive(Serialize, Clone, Debug, Default, PartialEq)]
pub struct State {
    /// play | pause | stop | offline (mpd not reachable)
    pub state: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub elapsed_s: Option<f64>,
    /// When `elapsed_s` was read (Unix ms), so a page can run the clock.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub elapsed_at_ms: Option<u64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub duration_s: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub position: Option<usize>,
    pub queue_length: usize,
    pub random: bool,
    pub repeat: bool,
    pub updating: bool,
}

pub struct Library {
    client: tokio::sync::Mutex<Option<Client>>,
    pub state: Mutex<State>,
    mounts: Mutex<String>,
    song_key: Mutex<Option<String>>,
}

impl Default for Library {
    fn default() -> Self {
        Library {
            client: tokio::sync::Mutex::new(None),
            state: Mutex::new(State { state: "offline".into(), ..State::default() }),
            mounts: Mutex::new(String::new()),
            song_key: Mutex::new(None),
        }
    }
}

fn now_ms() -> u64 {
    SystemTime::now().duration_since(UNIX_EPOCH).map(|d| d.as_millis() as u64).unwrap_or(0)
}

impl Library {
    /// Stay connected to mpd for the life of the daemon, refreshing on every
    /// change it reports. `changed` is poked after each refresh.
    pub async fn run(self: Arc<Self>, changed: impl Fn() + Send + 'static) {
        loop {
            let conn = match tokio::net::TcpStream::connect(ADDR).await {
                Ok(s) => Client::connect(s).await.ok(),
                Err(_) => None,
            };
            let Some((client, mut events)) = conn else {
                tokio::time::sleep(Duration::from_secs(2)).await;
                continue;
            };
            *self.client.lock().await = Some(client.clone());
            self.refresh(&client).await;
            changed();
            while let Some(ev) = events.next().await {
                match ev {
                    ConnectionEvent::SubsystemChange(
                        Subsystem::Player | Subsystem::Queue | Subsystem::Options | Subsystem::Update | Subsystem::Database,
                    ) => {
                        self.refresh(&client).await;
                        changed();
                    }
                    ConnectionEvent::SubsystemChange(_) => {}
                    ConnectionEvent::ConnectionClosed(_) => break,
                }
            }
            *self.client.lock().await = None;
            *self.state.lock().unwrap() = State { state: "offline".into(), ..State::default() };
            changed();
            tokio::time::sleep(Duration::from_secs(2)).await;
        }
    }

    async fn refresh(&self, c: &Client) {
        let Ok(st) = c.command(commands::Status).await else { return };
        let song = c.command(commands::CurrentSong).await.ok().flatten();
        let state = match st.state {
            PlayState::Playing => "play",
            PlayState::Paused => "pause",
            PlayState::Stopped => "stop",
        };
        *self.state.lock().unwrap() = State {
            state: state.into(),
            elapsed_s: st.elapsed.map(|d| d.as_secs_f64()),
            elapsed_at_ms: st.elapsed.map(|_| now_ms()),
            duration_s: st.duration.map(|d| d.as_secs_f64()),
            position: st.current_song.map(|(p, _)| p.0),
            queue_length: st.playlist_length,
            random: st.random,
            repeat: st.repeat,
            updating: st.update_job.is_some(),
        };

        // Now playing, in the shape every endpoint shares.
        let Some(s) = song else {
            meta::store(TAG, None);
            *self.song_key.lock().unwrap() = None;
            return;
        };
        let song = &s.song;
        let key = format!("{}#{}", s.id.0, song.url);
        let new_song = self.song_key.lock().unwrap().as_deref() != Some(key.as_str());
        let mut cover = meta::load(TAG).map(|m| m.cover).unwrap_or_default();
        if new_song {
            cover.clear();
            let _ = std::fs::remove_file(meta::cover_path(TAG));
            if let Ok(Some((bytes, _mime))) = c.album_art(&song.url).await {
                if std::fs::create_dir_all(meta::DIR).is_ok() && std::fs::write(meta::cover_path(TAG), &bytes).is_ok() {
                    cover = format!("cover/{TAG}?v={}", s.id.0);
                }
            }
            *self.song_key.lock().unwrap() = Some(key);
        }
        let title = song.title().map(str::to_string).unwrap_or_else(|| {
            // Untagged files: the file name without its extension.
            song.file_path().file_stem().map(|f| f.to_string_lossy().into_owned()).unwrap_or_default()
        });
        let m = meta::Meta {
            state: match state { "play" => "playing", "pause" => "paused", _ => "stopped" }.into(),
            title,
            artist: song.artists().join(", "),
            album: song.album().unwrap_or_default().to_string(),
            cover,
            client: String::new(),
            duration_ms: song.duration.or(st.duration).map(|d| d.as_millis() as u64),
        };
        meta::store(TAG, Some(&m));
    }

    async fn client(&self) -> Result<Client, String> {
        self.client.lock().await.clone().ok_or_else(|| "the library player is not running".into())
    }

    /// `cmd/audio/library/<verb>` with `arg`.
    pub async fn command(&self, verb: &str, arg: &str) -> Result<(), String> {
        let c = self.client().await?;
        let on = |a: &str| matches!(a.trim().to_ascii_uppercase().as_str(), "ON" | "1" | "TRUE" | "YES");
        fn e<T>(r: Result<T, mpd_client::client::CommandError>) -> Result<(), String> {
            r.map(|_| ()).map_err(|e| e.to_string())
        }
        // `add`, not addid (commands::Add): only `add` takes a folder, which
        // queues everything under it.
        let add = |uri: &str| mpd_client::protocol::Command::new("add").argument(uri.trim().to_string());
        match verb {
            "play" => match arg.trim().parse::<usize>() {
                Ok(pos) => e(c.command(commands::Play::song(commands::SongPosition(pos))).await),
                Err(_) => e(c.command(commands::Play::current()).await),
            },
            "pause" => e(c.command(commands::SetPause(true)).await),
            "toggle" => {
                let playing = self.state.lock().unwrap().state == "play";
                if playing {
                    e(c.command(commands::SetPause(true)).await)
                } else {
                    e(c.command(commands::Play::current()).await)
                }
            }
            "stop" => e(c.command(commands::Stop).await),
            "next" => e(c.command(commands::Next).await),
            "previous" => e(c.command(commands::Previous).await),
            "seek" => {
                let s: f64 = arg.trim().parse().map_err(|_| format!("seek: not seconds: {arg:?}"))?;
                e(c.raw_command(mpd_client::protocol::Command::new("seekcur").argument(format!("{:.1}", s.max(0.0)))).await)
            }
            "clear" => e(c.command(commands::ClearQueue).await),
            "add" => e(c.raw_command(add(arg)).await),
            "replace" => {
                e(c.command(commands::ClearQueue).await)?;
                e(c.raw_command(add(arg)).await)?;
                e(c.command(commands::Play::current()).await)
            }
            "random" => e(c.command(commands::SetRandom(on(arg))).await),
            "repeat" => e(c.command(commands::SetRepeat(on(arg))).await),
            "update" => e(c.raw_command(mpd_client::protocol::Command::new("update")).await),
            other => Err(format!("unknown library command '{other}'")),
        }
    }

    /// Re-index when a drive came or went (a mount under /media changed).
    pub async fn mounts_changed(&self) {
        let now: String = std::fs::read_to_string("/proc/mounts")
            .unwrap_or_default()
            .lines()
            .filter(|l| l.split_whitespace().nth(1).is_some_and(|m| m.starts_with("/media/")))
            .collect::<Vec<_>>()
            .join("\n");
        let changed = {
            let mut m = self.mounts.lock().unwrap();
            let c = *m != now;
            *m = now;
            c
        };
        if changed {
            if let Ok(c) = self.client().await {
                let _ = c.raw_command(mpd_client::protocol::Command::new("update")).await;
            }
        }
    }

    /// `lsinfo <path>`: the folders and tracks in one folder of /media.
    pub async fn browse(&self, path: &str) -> Result<Value, String> {
        let c = self.client().await?;
        let mut cmd = mpd_client::protocol::Command::new("lsinfo");
        if !path.trim_matches('/').is_empty() {
            cmd = cmd.argument(path.trim_matches('/').to_string());
        }
        let frame = c.raw_command(cmd).await.map_err(|e| e.to_string())?;
        Ok(json!(entries(frame.fields())))
    }

    /// `search any <q>`: tracks whose any tag matches, at most 200.
    pub async fn search(&self, q: &str) -> Result<Value, String> {
        let c = self.client().await?;
        let cmd = mpd_client::protocol::Command::new("search")
            .argument(format!("(any contains {})", quote(q)))
            .argument("window")
            .argument("0:200");
        let frame = c.raw_command(cmd).await.map_err(|e| e.to_string())?;
        Ok(json!(entries(frame.fields())))
    }
}

/// An mpd filter-expression string literal.
fn quote(s: &str) -> String {
    format!("\"{}\"", s.replace('\\', "\\\\").replace('"', "\\\""))
}

#[derive(Serialize, Debug, PartialEq)]
pub struct Entry {
    /// dir | file
    pub kind: &'static str,
    /// The mpd URI (path under /media).
    pub path: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub artist: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub album: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub duration_s: Option<f64>,
}

/// lsinfo/search output (key/value pairs; a `directory`, `file` or
/// `playlist` key starts a new entry) → entries. Playlists are skipped.
pub fn entries<'a>(fields: impl Iterator<Item = (&'a str, &'a str)>) -> Vec<Entry> {
    let mut out: Vec<Entry> = Vec::new();
    let mut skipping = false;
    for (k, v) in fields {
        match k {
            "directory" => {
                skipping = false;
                out.push(Entry { kind: "dir", path: v.into(), title: None, artist: None, album: None, duration_s: None });
            }
            "file" => {
                skipping = false;
                out.push(Entry { kind: "file", path: v.into(), title: None, artist: None, album: None, duration_s: None });
            }
            "playlist" => skipping = true,
            _ if skipping => {}
            "Title" => if let Some(e) = out.last_mut() { e.title = Some(v.into()) },
            "Artist" => if let Some(e) = out.last_mut() { e.artist.get_or_insert_with(|| v.into()); },
            "Album" => if let Some(e) = out.last_mut() { e.album = Some(v.into()) },
            "duration" => if let Some(e) = out.last_mut() { e.duration_s = v.parse().ok() },
            _ => {}
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn lsinfo_entries() {
        let f = [
            ("directory", "Sandisk/Music"),
            ("Last-Modified", "2026-01-01T00:00:00Z"),
            ("file", "Sandisk/Music/01 Song.flac"),
            ("Title", "Song"),
            ("Artist", "A"),
            ("Artist", "B"),
            ("Album", "LP"),
            ("duration", "201.5"),
            ("playlist", "Sandisk/x.m3u"),
            ("Title", "ignored"),
            ("file", "Sandisk/raw.mp3"),
        ];
        let e = entries(f.iter().copied());
        assert_eq!(e.len(), 3);
        assert_eq!((e[0].kind, e[0].path.as_str()), ("dir", "Sandisk/Music"));
        assert_eq!(e[1].title.as_deref(), Some("Song"));
        assert_eq!(e[1].artist.as_deref(), Some("A"));
        assert_eq!(e[1].duration_s, Some(201.5));
        assert_eq!((e[2].kind, e[2].title.as_deref()), ("file", None));
    }
    #[test]
    fn conf_plays_to_the_output_without_a_mixer() {
        let p = Port { id: "analog2".into(), label: "Analog 2".into(), device: "hw:CARD=Intel,DEV=2".into(), pcm: "ohc_analog2".into(), swap: false };
        let c = mpd_conf(&p);
        assert!(c.contains("music_directory \"/media\""));
        assert!(c.contains("bind_to_address \"127.0.0.1\""));
        assert!(c.contains("device \"ohc_analog2\""));
        assert!(c.contains("mixer_type \"none\""));
    }
    #[test]
    fn filter_strings_are_quoted() {
        assert_eq!(quote(r#"a "b" \c"#), r#""a \"b\" \\c""#);
    }
}
