//! Turning the map into running things.
//!
//! * `/etc/asound.conf`: every output becomes an ALSA dmix and every input a
//!   dsnoop at the board's rate (44.1 kHz: Spotify and AirPlay are both 44.1k
//!   sources, so nothing resamples). Any number of endpoints can then play into
//!   one jack at once — they mix — and an input can feed several outputs. In
//!   front of each output's dmix sit its level and duck stages (levels.rs):
//!
//!     <pcm>          plug → <pcm>_duck → <pcm>_vol → [swap] → dmix   music
//!     <pcm>_announce plug →              <pcm>_vol → [swap] → dmix   announcements
//! * one supervised process per endpoint: librespot per Spotify endpoint,
//!   shairport-sync (classic AirPlay; it hashes its device ID from the name, so
//!   N named instances are N devices) per AirPlay endpoint, alsaloop per route,
//!   plus any board helpers (the HC-800's ADV7513 keeper).
//!
//! Supervision is tokio's: each instance is a task that spawns the process with
//! kill_on_drop, logs its output, and restarts it 3 s after it exits. Stopping
//! an instance is aborting its task — the process dies with the dropped handle.
use crate::board::{Board, Port};
use crate::config::Endpoints;
use crate::levels;
use std::collections::HashMap;
use std::sync::{Arc, Mutex};
use std::time::Duration;
use tokio::io::{AsyncBufReadExt, BufReader};
use tokio::process::Command;
use tokio::task::JoinHandle;

pub const LIBRESPOT: &str = "/usr/bin/librespot";
pub const SHAIRPORT: &str = "/usr/bin/shairport-sync";
const RUN_DIR: &str = "/run/ohc/audio";

/// tag -> currently running.
pub type Up = Arc<Mutex<HashMap<String, bool>>>;

pub fn asound_conf(b: &Board) -> String {
    let mut s = String::from("# Generated by ohc-audiod from board.env — do not edit.\n");
    let mut key = 7100;
    for (kind, ports) in [("dmix", &b.outputs), ("dsnoop", &b.inputs)] {
        for p in ports {
            key += 1;
            s += &format!(
                "\n# {label}\npcm.{pcm}_{kind} {{\n    type {kind}\n    ipc_key {key}\n    ipc_perm 0666\n    slave {{\n        pcm \"{dev}\"\n        rate {rate}\n        format S16_LE\n        channels 2\n        period_size 1024\n        buffer_size 8192\n    }}\n}}\n",
                label = p.label.replace('"', "'"),
                pcm = p.pcm,
                dev = p.device,
                rate = b.rate,
            );
            // A swapped port gets a route plugin between plug and the shared
            // dmix/dsnoop, so everything that plays to it (or records from it)
            // is corrected, whoever opened it.
            let shared = if p.swap {
                s += &format!(
                    "pcm.{pcm}_swap {{\n    type route\n    slave {{\n        pcm \"{pcm}_{kind}\"\n        channels 2\n    }}\n    ttable.0.1 1\n    ttable.1.0 1\n}}\n",
                    pcm = p.pcm
                );
                format!("{}_swap", p.pcm)
            } else {
                format!("{}_{kind}", p.pcm)
            };
            if kind == "dsnoop" {
                s += &format!(
                    "pcm.{pcm} {{\n    type plug\n    slave.pcm \"{shared}\"\n    hint.description \"{label}\"\n}}\n",
                    pcm = p.pcm,
                    label = p.label.replace('"', "'"),
                );
                continue;
            }
            s += &output_stages(p, &shared);
        }
    }
    if let Some(first) = b.outputs.first() {
        s += &format!("\npcm.!default \"{}\"\n", first.pcm);
    }
    s
}

/// librespot's `--onevent` program: this binary as `--hook <tag>` (meta.rs).
fn librespot_hook(tag: &str) -> String {
    let me = std::env::current_exe().map(|p| p.display().to_string()).unwrap_or_else(|_| "/opt/ohc/bin/ohc-audiod".into());
    format!("#!/bin/sh\n# Generated by ohc-audiod: {tag}'s player events -> its metadata.\nexec {me} --hook {tag}\n")
}

/// An output's level and duck softvols, its music PCM and its announce PCM.
fn output_stages(p: &Port, shared: &str) -> String {
    let softvol = |name: &str, slave: &str, ctl: &str, min_db: f64, max: u32| {
        format!(
            "pcm.{name} {{\n    type softvol\n    slave.pcm \"{slave}\"\n    control {{\n        name \"{ctl}\"\n        card \"{card}\"\n    }}\n    min_dB {min_db:.1}\n    max_dB 0.0\n    resolution {res}\n}}\n",
            card = p.card(),
            res = max + 1,
        )
    };
    let (vol, duck) = (format!("{}_vol", p.pcm), format!("{}_duck", p.pcm));
    let mut s = softvol(&vol, shared, &levels::vol_control(p), levels::VOL_MIN_DB, levels::VOL_MAX);
    s += &softvol(&duck, &vol, &levels::duck_control(p), levels::DUCK_MIN_DB, levels::DUCK_MAX);
    s += &format!(
        "pcm.{pcm} {{\n    type plug\n    slave.pcm \"{duck}\"\n    hint.description \"{label}\"\n}}\npcm.{pcm}_announce {{\n    type plug\n    slave.pcm \"{vol}\"\n}}\n",
        pcm = p.pcm,
        label = p.label.replace('"', "'"),
    );
    s
}

/// A libconfig string literal (shairport-sync's config language).
fn libconfig_str(s: &str) -> String {
    format!("\"{}\"", s.replace('\\', "\\\\").replace('"', "\\\""))
}

/// The output's level control is AirPlay's hardware mixer (by its simple name,
/// `<pcm>`), so the AirPlay volume slider IS the output's level.
pub fn shairport_conf(name: &str, out: &Port, n: usize) -> String {
    format!(
        "general = {{\n    name = {};\n    port = {};\n    udp_port_base = {};\n    udp_port_range = 20;\n    output_backend = \"alsa\";\n    mdns_backend = \"avahi\";\n}};\nalsa = {{\n    output_device = {};\n    mixer_device = {};\n    mixer_control_name = {};\n}};\nmetadata = {{\n    enabled = \"yes\";\n    include_cover_art = \"yes\";\n    pipe_name = {pipe};\n}};\n",
        libconfig_str(name),
        5000 + n,
        6001 + 20 * n,
        libconfig_str(&out.pcm),
        libconfig_str(&format!("hw:{}", out.card())),
        libconfig_str(&out.pcm),
        pipe = libconfig_str(&crate::meta::fifo(&format!("airplay-{n}")).display().to_string()),
    )
}

/// One supervised instance.
pub struct Instance {
    pub tag: String,
    pub kind: &'static str,
    pub name: Option<String>,
    pub input: Option<String>,
    pub output: Option<String>,
    task: JoinHandle<()>,
}

impl Drop for Instance {
    fn drop(&mut self) {
        self.task.abort();
    }
}

fn supervise(tag: String, program: String, args: Vec<String>, up: Up) -> JoinHandle<()> {
    tokio::spawn(async move {
        loop {
            let mut cmd = Command::new(&program);
            cmd.args(&args)
                .stdin(std::process::Stdio::null())
                .stdout(std::process::Stdio::piped())
                .stderr(std::process::Stdio::piped())
                .kill_on_drop(true);
            match cmd.spawn() {
                Ok(mut child) => {
                    up.lock().unwrap().insert(tag.clone(), true);
                    for out in [child.stdout.take().map(|o| Box::new(o) as Box<dyn tokio::io::AsyncRead + Unpin + Send>),
                                child.stderr.take().map(|e| Box::new(e) as Box<dyn tokio::io::AsyncRead + Unpin + Send>)]
                        .into_iter()
                        .flatten()
                    {
                        let tag = tag.clone();
                        tokio::spawn(async move {
                            let mut lines = BufReader::new(out).lines();
                            while let Ok(Some(l)) = lines.next_line().await {
                                eprintln!("{tag}: {l}");
                            }
                        });
                    }
                    let st = child.wait().await;
                    eprintln!("{tag}: exited ({st:?}), restarting in 3 s");
                }
                Err(e) => eprintln!("{tag}: cannot start {program}: {e}"),
            }
            up.lock().unwrap().insert(tag.clone(), false);
            tokio::time::sleep(Duration::from_secs(3)).await;
        }
    })
}

pub fn write_asound(b: &Board) {
    if let Err(err) = std::fs::write("/etc/asound.conf", asound_conf(b)) {
        eprintln!("audiod: cannot write /etc/asound.conf: {err}");
    }
}

/// Start everything the map names (asound.conf written and the level controls
/// created first — see App::restart). The returned instances run until dropped.
pub fn start(b: &Board, e: &Endpoints, up: &Up) -> Vec<Instance> {
    up.lock().unwrap().clear();
    let _ = std::fs::create_dir_all(RUN_DIR);
    // Nothing plays until an endpoint says so.
    crate::meta::clear_all();
    let mut v = Vec::new();
    let have = |p: &str| std::path::Path::new(p).exists();

    if have(LIBRESPOT) {
        for (n, ep) in e.spotify.iter().enumerate() {
            let Some(out) = b.output(&ep.output) else { continue };
            let tag = format!("spotify-{n}");
            let hook = format!("{RUN_DIR}/{tag}-event");
            let hooked = std::fs::write(&hook, librespot_hook(&tag)).is_ok() && {
                use std::os::unix::fs::PermissionsExt;
                std::fs::set_permissions(&hook, std::fs::Permissions::from_mode(0o755)).is_ok()
            };
            let mut args: Vec<String> = vec![
                "--name".into(), ep.name.clone(),
                "--backend".into(), "alsa".into(),
                "--device".into(), out.pcm.clone(),
                "--bitrate".into(), "320".into(),
                "--disable-audio-cache".into(),
                "--zeroconf-port".into(), (5700 + n).to_string(),
                // The output's level is Spotify's mixer: the app's slider sets
                // it, and librespot starts from it rather than a default.
                "--mixer".into(), "alsa".into(),
                "--alsa-mixer-device".into(), format!("hw:{}", out.card()),
                "--alsa-mixer-control".into(), out.pcm.clone(),
            ];
            if hooked {
                args.extend(["--onevent".into(), hook]);
            }
            v.push(Instance { task: supervise(tag.clone(), LIBRESPOT.into(), args, up.clone()), tag,
                kind: "spotify", name: Some(ep.name.clone()), input: None, output: Some(ep.output.clone()) });
        }
    }
    if have(SHAIRPORT) {
        for (n, ep) in e.airplay.iter().enumerate() {
            let Some(out) = b.output(&ep.output) else { continue };
            let tag = format!("airplay-{n}");
            let cfg = format!("{RUN_DIR}/shairport-{n}.conf");
            if let Err(err) = std::fs::write(&cfg, shairport_conf(&ep.name, out, n)) {
                eprintln!("{tag}: cannot write {cfg}: {err}");
                continue;
            }
            v.push(Instance { task: supervise(tag.clone(), SHAIRPORT.into(), vec!["-c".into(), cfg], up.clone()), tag,
                kind: "airplay", name: Some(ep.name.clone()), input: None, output: Some(ep.output.clone()) });
        }
    }
    if have(crate::library::MPD) {
        if let Some((ep, out)) = e.library.first().and_then(|ep| b.output(&ep.output).map(|o| (ep, o))) {
            let tag = crate::library::TAG.to_string();
            let cfg = format!("{RUN_DIR}/mpd.conf");
            match std::fs::write(&cfg, crate::library::mpd_conf(out)) {
                Ok(()) => v.push(Instance {
                    task: supervise(tag.clone(), crate::library::MPD.into(), vec!["--no-daemon".into(), "--stderr".into(), cfg], up.clone()),
                    tag, kind: "library", name: Some(ep.name.clone()), input: None, output: Some(ep.output.clone()),
                }),
                Err(err) => eprintln!("library: cannot write {cfg}: {err}"),
            }
        }
    }
    for (n, r) in e.routes.iter().enumerate() {
        let (Some(i), Some(o)) = (b.input(&r.input), b.output(&r.output)) else { continue };
        let tag = format!("route-{n}");
        let args = vec![
            "-C".into(), i.pcm.clone(), "-P".into(), o.pcm.clone(),
            "-r".into(), b.rate.to_string(), "-c".into(), "2".into(), "-f".into(), "S16_LE".into(),
            "-t".into(), "50000".into(),
        ];
        v.push(Instance { task: supervise(tag.clone(), "alsaloop".into(), args, up.clone()), tag,
            kind: "route", name: None, input: Some(r.input.clone()), output: Some(r.output.clone()) });
    }
    for (n, h) in b.helpers.iter().enumerate().filter(|(_, h)| have(h)) {
        let tag = format!("helper-{n}");
        v.push(Instance { task: supervise(tag.clone(), h.clone(), vec![], up.clone()), tag,
            kind: "helper", name: Some(h.clone()), input: None, output: None });
    }
    v
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::board::Port;
    #[test]
    fn shairport_names_are_quoted_for_libconfig() {
        let out = Port { id: "hdmi".into(), label: "HDMI".into(), device: "hw:CARD=Intel,DEV=3".into(), pcm: "ohc_hdmi".into(), swap: false };
        let c = shairport_conf(r#"Den "TV" \ 2"#, &out, 1);
        assert!(c.contains(r#"name = "Den \"TV\" \\ 2";"#), "{c}");
        assert!(c.contains("port = 5001;"));
        assert!(c.contains("udp_port_base = 6021;"));
        assert!(c.contains(r#"output_device = "ohc_hdmi";"#));
        assert!(c.contains(r#"mixer_device = "hw:Intel";"#));
        assert!(c.contains(r#"mixer_control_name = "ohc_hdmi";"#));
        assert!(c.contains(r#"enabled = "yes";"#) && c.contains(r#"include_cover_art = "yes";"#), "{c}");
        assert!(c.contains(r#"pipe_name = "/run/ohc/audio/meta/airplay-1.pipe";"#));
    }
    #[test]
    fn asound_has_a_dmix_per_output_and_dsnoop_per_input() {
        let p = |id: &str, pcm: &str, d: &str| Port { id: id.into(), label: id.into(), device: d.into(), pcm: pcm.into(), swap: false };
        let b = Board {
            outputs: vec![p("analog1", "ohc_analog1", "hw:CARD=Intel,DEV=0"), p("hdmi", "ohc_hdmi", "hw:CARD=Intel,DEV=3")],
            inputs: vec![p("linein", "ohc_in_linein", "hw:CARD=Intel,DEV=0")],
            rate: 44100, helpers: vec![],
        };
        let a = asound_conf(&b);
        assert!(a.contains("pcm.ohc_analog1_dmix {"));
        assert!(a.contains("pcm.ohc_hdmi_dmix {"));
        assert!(a.contains("pcm.ohc_in_linein_dsnoop {"));
        assert!(a.contains("pcm \"hw:CARD=Intel,DEV=3\""));
        assert!(a.contains("pcm.!default \"ohc_analog1\""));
        assert_eq!(a.matches("ipc_key").count(), 3);
    }
    #[test]
    fn librespot_hook_runs_this_binary() {
        let h = librespot_hook("spotify-2");
        assert!(h.starts_with("#!/bin/sh\n"));
        assert!(h.trim_end().ends_with(" --hook spotify-2"), "{h}");
    }
    #[test]
    fn music_is_ducked_and_announcements_are_not() {
        let b = Board {
            outputs: vec![Port { id: "analog1".into(), label: "Analog 1".into(), device: "hw:CARD=Intel,DEV=0".into(), pcm: "ohc_analog1".into(), swap: false }],
            inputs: vec![], rate: 44100, helpers: vec![],
        };
        let a = asound_conf(&b);
        assert!(a.contains("pcm.ohc_analog1_vol {\n    type softvol\n    slave.pcm \"ohc_analog1_dmix\""), "{a}");
        assert!(a.contains("name \"ohc_analog1 Playback Volume\"\n        card \"Intel\""));
        assert!(a.contains("pcm.ohc_analog1_duck {\n    type softvol\n    slave.pcm \"ohc_analog1_vol\""));
        assert!(a.contains("name \"ohc_analog1 Duck Playback Volume\""));
        assert!(a.contains("pcm.ohc_analog1 {\n    type plug\n    slave.pcm \"ohc_analog1_duck\""));
        assert!(a.contains("pcm.ohc_analog1_announce {\n    type plug\n    slave.pcm \"ohc_analog1_vol\""));
        assert!(a.contains("resolution 256") && a.contains("resolution 201"));
    }
    #[test]
    fn a_swapped_port_routes_through_a_channel_swap() {
        let b = Board {
            outputs: vec![Port { id: "analog2".into(), label: "Analog 2".into(), device: "hw:CARD=Intel,DEV=2".into(), pcm: "ohc_analog2".into(), swap: true }],
            inputs: vec![], rate: 44100, helpers: vec![],
        };
        let a = asound_conf(&b);
        assert!(a.contains("pcm.ohc_analog2_swap {\n    type route"), "{a}");
        assert!(a.contains("ttable.0.1 1") && a.contains("ttable.1.0 1"));
        assert!(a.contains("pcm.ohc_analog2_vol {\n    type softvol\n    slave.pcm \"ohc_analog2_swap\""), "{a}");
        assert!(a.contains("pcm \"ohc_analog2_dmix\""));
    }
}
