//! Turning the map into running things.
//!
//! * `/etc/asound.conf`: every output becomes an ALSA dmix and every input a
//!   dsnoop at the board's rate (44.1 kHz: Spotify and AirPlay are both 44.1k
//!   sources, so nothing resamples). Any number of endpoints can then play into
//!   one jack at once — they mix — and an input can feed several outputs.
//! * one supervised process per endpoint: librespot per Spotify endpoint,
//!   shairport-sync (classic AirPlay; it hashes its device ID from the name, so
//!   N named instances are N devices) per AirPlay endpoint, alsaloop per route,
//!   plus any board helpers (the HC-800's ADV7513 keeper).
//!
//! Supervision is tokio's: each instance is a task that spawns the process with
//! kill_on_drop, logs its output, and restarts it 3 s after it exits. Stopping
//! an instance is aborting its task — the process dies with the dropped handle.
use crate::board::Board;
use crate::config::Endpoints;
use std::collections::HashMap;
use std::sync::{Arc, Mutex};
use std::time::Duration;
use tokio::io::{AsyncBufReadExt, BufReader};
use tokio::process::Command;
use tokio::task::JoinHandle;

pub const LIBRESPOT: &str = "/usr/bin/librespot";
pub const SHAIRPORT: &str = "/usr/bin/shairport-sync";
const RUN_DIR: &str = "/run/ohc/audio";

/// tag -> currently running.
pub type Up = Arc<Mutex<HashMap<String, bool>>>;

pub fn asound_conf(b: &Board) -> String {
    let mut s = String::from("# Generated by ohc-audiod from board.env — do not edit.\n");
    let mut key = 7100;
    for (kind, ports) in [("dmix", &b.outputs), ("dsnoop", &b.inputs)] {
        for p in ports {
            key += 1;
            s += &format!(
                "\n# {label}\npcm.{pcm}_{kind} {{\n    type {kind}\n    ipc_key {key}\n    ipc_perm 0666\n    slave {{\n        pcm \"{dev}\"\n        rate {rate}\n        format S16_LE\n        channels 2\n        period_size 1024\n        buffer_size 8192\n    }}\n}}\npcm.{pcm} {{\n    type plug\n    slave.pcm \"{pcm}_{kind}\"\n    hint.description \"{label}\"\n}}\n",
                label = p.label.replace('"', "'"),
                pcm = p.pcm,
                dev = p.device,
                rate = b.rate,
            );
        }
    }
    if let Some(first) = b.outputs.first() {
        s += &format!("\npcm.!default \"{}\"\n", first.pcm);
    }
    s
}

/// A libconfig string literal (shairport-sync's config language).
fn libconfig_str(s: &str) -> String {
    format!("\"{}\"", s.replace('\\', "\\\\").replace('"', "\\\""))
}

pub fn shairport_conf(name: &str, pcm: &str, n: usize) -> String {
    format!(
        "general = {{\n    name = {};\n    port = {};\n    udp_port_base = {};\n    udp_port_range = 20;\n    output_backend = \"alsa\";\n    mdns_backend = \"avahi\";\n}};\nalsa = {{\n    output_device = {};\n}};\nmetadata = {{\n    enabled = \"no\";\n}};\n",
        libconfig_str(name),
        5000 + n,
        6001 + 20 * n,
        libconfig_str(pcm)
    )
}

/// One supervised instance.
pub struct Instance {
    pub tag: String,
    pub kind: &'static str,
    pub name: Option<String>,
    pub input: Option<String>,
    pub output: Option<String>,
    task: JoinHandle<()>,
}

impl Drop for Instance {
    fn drop(&mut self) {
        self.task.abort();
    }
}

fn supervise(tag: String, program: String, args: Vec<String>, up: Up) -> JoinHandle<()> {
    tokio::spawn(async move {
        loop {
            let mut cmd = Command::new(&program);
            cmd.args(&args)
                .stdin(std::process::Stdio::null())
                .stdout(std::process::Stdio::piped())
                .stderr(std::process::Stdio::piped())
                .kill_on_drop(true);
            match cmd.spawn() {
                Ok(mut child) => {
                    up.lock().unwrap().insert(tag.clone(), true);
                    for out in [child.stdout.take().map(|o| Box::new(o) as Box<dyn tokio::io::AsyncRead + Unpin + Send>),
                                child.stderr.take().map(|e| Box::new(e) as Box<dyn tokio::io::AsyncRead + Unpin + Send>)]
                        .into_iter()
                        .flatten()
                    {
                        let tag = tag.clone();
                        tokio::spawn(async move {
                            let mut lines = BufReader::new(out).lines();
                            while let Ok(Some(l)) = lines.next_line().await {
                                eprintln!("{tag}: {l}");
                            }
                        });
                    }
                    let st = child.wait().await;
                    eprintln!("{tag}: exited ({st:?}), restarting in 3 s");
                }
                Err(e) => eprintln!("{tag}: cannot start {program}: {e}"),
            }
            up.lock().unwrap().insert(tag.clone(), false);
            tokio::time::sleep(Duration::from_secs(3)).await;
        }
    })
}

/// Write asound.conf and start everything the map names. The returned
/// instances run until dropped.
pub fn start(b: &Board, e: &Endpoints, up: &Up) -> Vec<Instance> {
    up.lock().unwrap().clear();
    if let Err(err) = std::fs::write("/etc/asound.conf", asound_conf(b)) {
        eprintln!("audiod: cannot write /etc/asound.conf: {err}");
    }
    let _ = std::fs::create_dir_all(RUN_DIR);
    let mut v = Vec::new();
    let have = |p: &str| std::path::Path::new(p).exists();

    if have(LIBRESPOT) {
        for (n, ep) in e.spotify.iter().enumerate() {
            let Some(out) = b.output(&ep.output) else { continue };
            let tag = format!("spotify-{n}");
            let args = vec![
                "--name".into(), ep.name.clone(),
                "--backend".into(), "alsa".into(),
                "--device".into(), out.pcm.clone(),
                "--bitrate".into(), "320".into(),
                "--disable-audio-cache".into(),
                "--zeroconf-port".into(), (5700 + n).to_string(),
            ];
            v.push(Instance { task: supervise(tag.clone(), LIBRESPOT.into(), args, up.clone()), tag,
                kind: "spotify", name: Some(ep.name.clone()), input: None, output: Some(ep.output.clone()) });
        }
    }
    if have(SHAIRPORT) {
        for (n, ep) in e.airplay.iter().enumerate() {
            let Some(out) = b.output(&ep.output) else { continue };
            let tag = format!("airplay-{n}");
            let cfg = format!("{RUN_DIR}/shairport-{n}.conf");
            if let Err(err) = std::fs::write(&cfg, shairport_conf(&ep.name, &out.pcm, n)) {
                eprintln!("{tag}: cannot write {cfg}: {err}");
                continue;
            }
            v.push(Instance { task: supervise(tag.clone(), SHAIRPORT.into(), vec!["-c".into(), cfg], up.clone()), tag,
                kind: "airplay", name: Some(ep.name.clone()), input: None, output: Some(ep.output.clone()) });
        }
    }
    for (n, r) in e.routes.iter().enumerate() {
        let (Some(i), Some(o)) = (b.input(&r.input), b.output(&r.output)) else { continue };
        let tag = format!("route-{n}");
        let args = vec![
            "-C".into(), i.pcm.clone(), "-P".into(), o.pcm.clone(),
            "-r".into(), b.rate.to_string(), "-c".into(), "2".into(), "-f".into(), "S16_LE".into(),
            "-t".into(), "50000".into(),
        ];
        v.push(Instance { task: supervise(tag.clone(), "alsaloop".into(), args, up.clone()), tag,
            kind: "route", name: None, input: Some(r.input.clone()), output: Some(r.output.clone()) });
    }
    for (n, h) in b.helpers.iter().enumerate().filter(|(_, h)| have(h)) {
        let tag = format!("helper-{n}");
        v.push(Instance { task: supervise(tag.clone(), h.clone(), vec![], up.clone()), tag,
            kind: "helper", name: Some(h.clone()), input: None, output: None });
    }
    v
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::board::Port;
    #[test]
    fn shairport_names_are_quoted_for_libconfig() {
        let c = shairport_conf(r#"Den "TV" \ 2"#, "ohc_hdmi", 1);
        assert!(c.contains(r#"name = "Den \"TV\" \\ 2";"#), "{c}");
        assert!(c.contains("port = 5001;"));
        assert!(c.contains("udp_port_base = 6021;"));
        assert!(c.contains(r#"output_device = "ohc_hdmi";"#));
    }
    #[test]
    fn asound_has_a_dmix_per_output_and_dsnoop_per_input() {
        let p = |id: &str, pcm: &str, d: &str| Port { id: id.into(), label: id.into(), device: d.into(), pcm: pcm.into() };
        let b = Board {
            outputs: vec![p("analog1", "ohc_analog1", "hw:CARD=Intel,DEV=0"), p("hdmi", "ohc_hdmi", "hw:CARD=Intel,DEV=3")],
            inputs: vec![p("linein", "ohc_in_linein", "hw:CARD=Intel,DEV=0")],
            rate: 44100, helpers: vec![],
        };
        let a = asound_conf(&b);
        assert!(a.contains("pcm.ohc_analog1_dmix {"));
        assert!(a.contains("pcm.ohc_hdmi_dmix {"));
        assert!(a.contains("pcm.ohc_in_linein_dsnoop {"));
        assert!(a.contains("pcm \"hw:CARD=Intel,DEV=3\""));
        assert!(a.contains("pcm.!default \"ohc_analog1\""));
        assert_eq!(a.matches("ipc_key").count(), 3);
    }
}
