/* Minimal TM4C1231D5 register map — only what this firmware touches.
 *
 * Hand-written from the TM4C123x datasheet rather than pulling in TivaWare, so
 * the whole firmware stays under a licence we control and has no vendor code in
 * it. Peripheral choice is dictated by the stock image's own usage, recovered by
 * analysis (docs/io-mcu-firmware.md): UART0 is the host link, UART5/UART7 are
 * the two user serial ports, TIMER0-3 drive IR.
 */
#ifndef OHC_TM4C_H
#define OHC_TM4C_H

#include <stdbool.h>
#include <stdint.h>

#define REG(a) (*(volatile uint32_t *)(a))

/* System control */
#define SYSCTL_BASE   0x400FE000u
#define SYSCTL_RCC    REG(SYSCTL_BASE + 0x060)
#define SYSCTL_RCC2   REG(SYSCTL_BASE + 0x070)
#define SYSCTL_RIS    REG(SYSCTL_BASE + 0x050)
#define SYSCTL_RCGCUART REG(SYSCTL_BASE + 0x618)
#define SYSCTL_RCGCGPIO REG(SYSCTL_BASE + 0x608)
#define SYSCTL_RCGCTIMER REG(SYSCTL_BASE + 0x604)
#define SYSCTL_RCGCWTIMER REG(SYSCTL_BASE + 0x65C)  /* wide timers live here */
#define SYSCTL_PRUART REG(SYSCTL_BASE + 0xA18)
#define SYSCTL_PRGPIO REG(SYSCTL_BASE + 0xA08)

#define RCC2_USERCC2   (1u << 31)
#define RCC2_DIV400    (1u << 30)
#define RCC2_SYSDIV2_S 22
/* With DIV400 the divisor is the 7-bit {SYSDIV2[28:23], SYSDIV2LSB[22]} =
 * RCC2[28:22]. Masking only 6 bits leaves bit 28 stale. */
#define RCC2_SYSDIV2_M (0x7Fu << RCC2_SYSDIV2_S)
#define RCC2_PWRDN2    (1u << 13)
#define RCC2_BYPASS2   (1u << 11)
#define RCC2_OSCSRC2_S 4
#define RCC_MOSCDIS    (1u << 0)
#define RCC_XTAL_S     6
#define RCC_XTAL_16MHZ (0x15u << RCC_XTAL_S)
#define RCC_OSCSRC_S   4
#define RCC_BYPASS     (1u << 11)
#define RCC_USESYSDIV  (1u << 22)
#define RIS_PLLLRIS    (1u << 6)
#define SYSCTL_MISC    REG(SYSCTL_BASE + 0x058)
#define MISC_PLLLMIS   (1u << 6)

/* GPIO — APB apertures.
 *
 * NOT the AHB aliases (0x4005_8000+). Those are unmapped out of reset and stay
 * unmapped until the matching bit is set in SYSCTL_GPIOHBCTL (0x400FE06C);
 * touching them before that reads as zero and writes go nowhere, so a UART
 * muxed through AHB simply never comes up — with no error to notice.
 *
 * APB costs an extra bus cycle per access, which buys us nothing here: the IR
 * carrier is generated by timer hardware, not by toggling a pin, so no GPIO
 * access is on a timing-critical path. (The stock application agrees — its
 * literal pool holds 238 APB references against 12 AHB.)
 */
#define GPIOA_BASE 0x40004000u
#define GPIOB_BASE 0x40005000u
#define GPIOC_BASE 0x40006000u
#define GPIOD_BASE 0x40007000u
#define GPIOE_BASE 0x40024000u
#define GPIOF_BASE 0x40025000u
#define SYSCTL_GPIOHBCTL REG(SYSCTL_BASE + 0x06C)  /* only if AHB is ever wanted */
#define GPIO_DIR(b)   REG((b) + 0x400)
#define GPIO_AFSEL(b) REG((b) + 0x420)
#define GPIO_DR2R(b)  REG((b) + 0x500)
#define GPIO_PUR(b)   REG((b) + 0x510)
#define GPIO_DEN(b)   REG((b) + 0x51C)
#define GPIO_LOCK(b)  REG((b) + 0x520)
#define GPIO_CR(b)    REG((b) + 0x524)
#define GPIO_PCTL(b)  REG((b) + 0x52C)
#define GPIO_DATA(b)  REG((b) + 0x3FC)   /* all pins */

/* UART */
#define UART0_BASE 0x4000C000u
#define UART4_BASE 0x40010000u
#define UART5_BASE 0x40011000u
#define UART7_BASE 0x40013000u
#define UART_DR(b)    REG((b) + 0x000)
#define UART_FR(b)    REG((b) + 0x018)
#define UART_IBRD(b)  REG((b) + 0x024)
#define UART_FBRD(b)  REG((b) + 0x028)
#define UART_LCRH(b)  REG((b) + 0x02C)
#define UART_CTL(b)   REG((b) + 0x030)
#define UART_IFLS(b)  REG((b) + 0x034)
#define UART_IM(b)    REG((b) + 0x038)
#define UART_MIS(b)   REG((b) + 0x040)
#define UART_ICR(b)   REG((b) + 0x044)
#define UART_CC(b)    REG((b) + 0xFC8)
#define UART_FR_RXFE  (1u << 4)
#define UART_FR_TXFF  (1u << 5)
#define UART_FR_BUSY  (1u << 3)
#define UART_LCRH_WLEN8 (0x3u << 5)
#define UART_LCRH_FEN   (1u << 4)
#define UART_CTL_UARTEN (1u << 0)
#define UART_CTL_TXE    (1u << 8)
#define UART_CTL_RXE    (1u << 9)

/* General-purpose timers (IR carrier + capture) */
#define TIMER0_BASE 0x40030000u
#define TIMER1_BASE 0x40031000u
#define TIMER2_BASE 0x40032000u
#define TIMER3_BASE 0x40033000u
#define TIMER4_BASE 0x40034000u
#define TIMER5_BASE 0x40035000u
#define WTIMER0_BASE 0x40036000u
#define WTIMER1_BASE 0x40037000u
#define WTIMER2_BASE 0x4004C000u
#define WTIMER3_BASE 0x4004D000u
#define WTIMER4_BASE 0x4004E000u
#define WTIMER5_BASE 0x4004F000u
#define TIMER_CFG(b)   REG((b) + 0x000)
#define TIMER_TAMR(b)  REG((b) + 0x004)
#define TIMER_CTL(b)   REG((b) + 0x00C)
#define TIMER_IMR(b)   REG((b) + 0x018)
#define TIMER_RIS(b)   REG((b) + 0x01C)
#define TIMER_ICR(b)   REG((b) + 0x024)
#define TIMER_TAILR(b) REG((b) + 0x028)
#define TIMER_TAMATCHR(b) REG((b) + 0x030)
#define TIMER_TAPR(b)  REG((b) + 0x038)
#define TIMER_TAV(b)   REG((b) + 0x050)

#define TIMER_CFG_16BIT     0x04u
#define TIMER_CFG_32BIT     0x00u
#define TIMER_TAMR_PERIODIC 0x02u
#define TIMER_TAMR_TAAMS    (1u << 3)   /* alternate mode: PWM */
#define TIMER_TAMR_TACMR    (1u << 2)   /* capture mode: edge-time */
#define TIMER_TAMR_CAPTURE  0x03u
#define TIMER_CTL_TAEN      (1u << 0)
#define TIMER_CTL_TAPWML    (1u << 6)   /* invert PWM output */
#define TIMER_CTL_TAEVENT_BOTH (0x3u << 2)
#define TIMER_ICR_TATOCINT  (1u << 0)
#define TIMER_RIS_TATORIS   (1u << 0)

/* ── IR ───────────────────────────────────────────────────────────────────
 *
 * Carrier generation uses a 16-bit general-purpose timer in PWM mode, so the
 * carrier is produced by HARDWARE and keeps running at an exact frequency while
 * the CPU does other things. Gating it per burst is then just enabling and
 * disabling the timer, which is glitch-free and jitter-free — doing it by
 * toggling a pin in software would put every interrupt's latency straight into
 * the waveform, and IR receivers reject a carrier that wanders.
 */
/* This part has NO PWM module — TM4C1231D5PM's DC1/DC3/DC5 PWM-presence bits
 * read 0. The carrier comes from a general-purpose timer's CCP output in PWM
 * mode. Which pin belongs to which channel is in ir_pins.h, extracted from the
 * stock firmware.
 */
void ir_carrier_configure(uint8_t channel, uint32_t carrier_ticks);
void ir_carrier_set(uint8_t channel, bool on);
void ir_burst_timer_start(uint32_t ticks);
bool ir_burst_timer_expired(void);

/* Cortex-M4 SysTick */
#define SYSTICK_CTRL  REG(0xE000E010u)
#define SYSTICK_LOAD  REG(0xE000E014u)
#define SYSTICK_VAL   REG(0xE000E018u)

/* The clock the firmware runs at. The stock image reports IR capture periods in
 * timer ticks; our host-side decoder assumes 50 MHz (see MCU_TIMER_HZ in
 * packages/ohc-iod/src/mcu.rs), so keep the two in step. */
#define OHC_SYSCLK_HZ 50000000u

/* Host link speed. NOT 115200 — see docs/io-mcu-firmware.md. */
#define OHC_HOST_BAUD 460800u

void tm4c_clock_init(void);
void tm4c_uart_init(uint32_t base, uint32_t baud);
void tm4c_uart_putc(uint32_t base, uint8_t c);
int  tm4c_uart_getc(uint32_t base);          /* -1 when the RX FIFO is empty */
void tm4c_delay_us(uint32_t us);

#endif /* OHC_TM4C_H */
